export const cardsInfo = [
  {
    id: "0",
    logoImage: "ferrari-logo.png",
    logoTextImage: "ferrari-logo-text.png",
    brandName: "FERRARI",
    model: "SF90 Stradale",
    zeroToHundred: "2.5",
    zeroToHundredText: "seconds",
    topSpeed: "340",
    topSpeedText: "km/h (211 mph)",
    torque: "800",
    torqueText: "Nm",
    engine: "4.0-liter twin-turbo V8 with 769 horsepower + 3 electric motors",
    ability: "Hybrid powertrain and advanced aerodynamics",
    website: "www.ferrari.com",
    websiteURL: "https://www.ferrari.com/en-EN/auto/sf90-stradale",
  },
  {
    id: "1",
    logoImage: "porsche-logo.png",
    logoTextImage: "porsche-logo-text.png",
    brandName: "PORSCHE",
    model: "911 GT2 RS",
    zeroToHundred: "2.7",
    zeroToHundredText: "seconds",
    topSpeed: "211",
    topSpeedText: "mph (340 km/h)",
    torque: "750",
    torqueText: "Nm",
    engine: "3.8-liter twin-turbo flat-six engine with 700 horsepower",
    ability:
      "Lightweight design and advanced aerodynamics for maximum performance",
    website: "www.porsche.com",
    websiteURL:
      "https://www.porsche.com/international/models/911/911-gt3-models/",
  },
  {
    id: "2",
    logoImage: "lamborghini-logo.png",
    logoTextImage: "lamborghini-logo-text.png",
    brandName: "LAMBORGHINI",
    model: "Aventador SVJ",
    zeroToHundred: "2.8",
    zeroToHundredText: "seconds",
    topSpeed: "350",
    topSpeedText: "km/h (217 mph)",
    torque: "720",
    torqueText: "Nm",
    engine: "6.5-liter V12 with 770 horsepower",
    ability: "Aerodynamic optimizations and all-wheel drive system",
    website: "www.lamborghini.com",
    websiteURL: "https://www.lamborghini.com/en-en/history/aventador-svj",
  },
];
